### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by navyhod** [wtfil/google-music-sync#4]
Hi !

Is there any hope that you'll fix this error ? :) I tried to debug it, but I don't have such experience in npm/JS.

Thanks !

Full stack trace:

Downloading [--------------------------------------------------] 0% 0.0sinternal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at runApplescript (/usr/local/lib/node_modules/google-music-sync/node_modules/applescript/lib/applescript.js:38:21)
    at Object.execString (/usr/local/lib/node_modules/google-music-sync/node_modules/applescript/lib/applescript.js:19:10)
    at Object.createPlaylist (/usr/local/lib/node_modules/google-music-sync/node_modules/itunes-control/index.js:11:14)
    at downloadPlalist (/usr/local/lib/node_modules/google-music-sync/lib/download.js:132:10)
    at downloadSongs (/usr/local/lib/node_modules/google-music-sync/cli-actions.js:18:2)
    at next (/usr/local/lib/node_modules/google-music-sync/cli-actions.js:31:11)
    at /usr/local/lib/node_modules/google-music-sync/lib/providers/google.js:127:3

**Comment by navyhod** [comment]
UPD: As far as I understand there is a library that using code from iOS. However I'm on linux and don't know how to make it work.
